# Generated by Django 5.0.8 on 2024-08-17 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'permissions': [('advanced', 'Advanced Perm'), ('pro', 'Pro Perm'), ('basic', 'basic Perm'), ('basic AI', 'Basic AI Perm')]},
        ),
    ]
