# Generated by Django 5.0.8 on 2024-08-20 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0012_alter_subscriptionprice_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionprice',
            options={},
        ),
    ]
