# Generated by Django 5.0.8 on 2024-08-20 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0015_alter_subscriptionprice_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionprice',
            name='features',
            field=models.TextField(blank=True, help_text='features for pricing, seperated by new line', null=True),
        ),
    ]
