# Generated by Django 5.0.8 on 2024-08-14 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0002_pagevisits_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='pageVisits',
            new_name='PageVisit',
        ),
    ]
